import os
from typing import List
import spacy
from joblib import load

# !!! Autogenerated !!! Do not change. Path where this python file is located
home = os.path.dirname(os.path.realpath(__file__))

# !!! Autogenerated !!! Do not change the class name
class QulogRf:
    def __init__(self): 
        # !!! Autogenerated !!! Do not change.
        self.model = self.load(os.path.join(home, './model'))

        self.nlp = spacy.load('en_core_web_trf')
        self.nlp_parse = spacy.load('en_core_web_sm')

    # !!! Autogenerated !!! Do not change the method name.
    def load(self, model_file_path):
        return load(model_file_path)

    def _get_trf_embedding(self, doc):
        return doc._.trf_data.tensors[-1].ravel()


    def _get_trf_embeddings(self, trf_docs):
        embeddings = []
        for doc in trf_docs:
            embeddings.append(self._get_trf_embedding(doc))
        return embeddings

    def _get_word_class_embeddings(self, log_lines):
        docs = list(self.nlp_parse.pipe(log_lines))
        word_classses = [" ".join([t.pos_ for t in doc]) for doc in docs]
        word_classs_trf_docs = list(self.nlp.pipe(word_classses))
        word_class_embeddings = self._get_trf_embeddings(word_classs_trf_docs)
        return word_class_embeddings

    # !!! Autogenerated !!! Do not change the method name.
    def predict(self, log_line: str):
        return self.predict_batch([log_line])[0]

    # !!! Autogenerated !!! Do not change the method name.
    def predict_batch(self, log_lines: List[str]):
        word_class_embeddings = self._get_word_class_embeddings(log_lines)
        predictions = self.model.predict(word_class_embeddings)
        return predictions


# !!! Autogenerated !!! This will be used as a simple functionality test
if __name__ == "__main__":
    q = QulogRf()
    s = "This is a log message"
    p1 = q.predict(s)
    p2 = q.predict_batch([s])
    print("Prediction for '{}': {}".format(s, p1))
    print("Prediction for '{}': {}".format(s, p2[0]))